language: c

sudo: false

os:
  - linux
  - osx

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update &&
      brew install qt5 &&
      brew link --force qt5 &&
      brew install sdl;
    fi
  - if [ ! -f deps/bass24-$TRAVIS_OS_NAME.zip ]; then
        mkdir -p deps && (
            cd deps &&
            wget http://www.un4seen.com/files/bass24-$TRAVIS_OS_NAME.zip -O bass24-$TRAVIS_OS_NAME.zip
        )
    fi &&
    mkdir examples/include &&
    mkdir examples/lib &&
    unzip -d bass24 deps/bass24-$TRAVIS_OS_NAME.zip &&
    cp bass24/bass.h examples/include/;
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      cp bass24/libbass.dylib examples/lib/;
    fi;
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      cp bass24/x64/libbass.so examples/lib/;
    fi

script:
  - make &&
    make examples/example_bass &&
    make examples/example_bass-player

cache:
  directories:
    - deps

addons:
  apt:
    packages:
      - libsdl1.2-dev
