version: '{build}'

environment:
  matrix:
  - platform: x64
    cc: VS2013
    QTDIR: C:\Qt\5.5\msvc2013_64
  - platform: Win32
    cc: VS2013
    QTDIR: C:\Qt\5.5\msvc2013

configuration:
  - Release

cache:
  - packages -> **\packages.config
  - bass24.zip

install:
  - nuget restore examples.vs2013.sln
  # download and install bass
  - if not exist bass24.zip curl -fsS -o bass24.zip http://www.un4seen.com/files/bass24.zip
  - 7z x -obass24 bass24.zip > NUL
  - mkdir examples\lib
  - mkdir examples\lib64
  - mkdir examples\include
  - copy bass24\c\bass.lib examples\lib
  - copy bass24\c\x64\bass.lib examples\lib64
  - copy bass24\c\bass.h examples\include

before_build:
  - set PATH=%QTDIR%\bin;%PATH%

build_script:
  - msbuild examples.vs2013.sln
  - msbuild examples.vs2013.sln /property:Configuration="Release Client"
  - cd editor
  - qmake -tp vc editor.pro
  - msbuild

after_build:
  - mkdir staging
  - cd staging
  - copy ..\release\editor.exe .
  - windeployqt --release editor.exe

artifacts:
  - path: editor\staging
    name: editor
